/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author INTEGRAL COMPUTER
 */
public class duplicate_provides extends javax.swing.JFrame {

    /**
     * Creates new form duplicate_provides
     */
    public duplicate_provides() {
        initComponents();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select Toolid from provides");
            while(rs.next())
            {
                cmbToolid.addItem(String.valueOf(rs.getInt(1)));
            }
             } catch (SQLException qw) {
            System.out.println(qw);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        txttoolname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbToolid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 10));

        jPanel4.setBackground(new java.awt.Color(204, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\arrow-241-64.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CANCLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 170, 300));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 90, 40));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel11.setText("P R O V I D E S");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 200, 40));

        jLabel12.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel12.setText("Tool Name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 40));

        txtquantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtquantity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 30));

        txttoolname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttoolname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txttoolname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, 30));

        jLabel13.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        jLabel13.setText("TOOL Id");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 40));

        cmbToolid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbToolid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbToolid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbToolidItemStateChanged(evt);
            }
        });
        jPanel5.add(cmbToolid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            String Toolid,ToolName,Quantity;
            String search =cmbToolid.getSelectedItem().toString();
            Toolid=cmbToolid.getSelectedItem().toString();      
            ToolName= txttoolname.getText();
            Quantity= txtquantity.getText();
           st.executeUpdate("update provides set ToolName='"+txttoolname.getText()+"',Quantity='"+txtquantity.getText()+"' where Toolid='"+search+"'");
            con.close();
        } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbToolidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbToolidItemStateChanged
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from provides where Toolid="+cmbToolid.getSelectedItem()+"");
            rs.next();
            txttoolname.setText(rs.getString(2));
            txtquantity.setText(rs.getString(3));
          
            
             } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_cmbToolidItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(duplicate_provides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(duplicate_provides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(duplicate_provides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(duplicate_provides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new duplicate_provides().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbToolid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txttoolname;
    // End of variables declaration//GEN-END:variables
}
