/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author INTEGRAL COMPUTER
 */
public class Fees_9 extends javax.swing.JFrame {

    /**
     * Creates new form Fees_9
     */
    public Fees_9() {
        initComponents();
        //Sports Details
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select Sportsid from sportdetails");
            while(rs.next())
            {
                cmbSportsId.addItem(String.valueOf(rs.getInt(1)));
            }
             } catch (SQLException qw) {
            System.out.println(qw);
        }
         //Players Details
           try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select PlayerId from register1");
            while(rs.next())
            {
                cmbPlayerid.addItem(String.valueOf(rs.getInt(1)));
            }
             } catch (SQLException qw) {
            System.out.println(qw);
        }
           //Coach Details
           try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select coachid from coachdetails");
            while(rs.next())
            {
                cmbCoachId.addItem(String.valueOf(rs.getInt(1)));
            }
             } catch (SQLException qw) {
            System.out.println(qw);
        }
           //Provides Details
            try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select Toolid from provides");
            while(rs.next())
            {
                cmbToolId.addItem(String.valueOf(rs.getInt(1)));
            }
             } catch (SQLException qw) {
            System.out.println(qw);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        cmbToolId = new javax.swing.JComboBox<>();
        cmbPlayerid = new javax.swing.JComboBox<>();
        cmbCoachId = new javax.swing.JComboBox<>();
        cmbSportsId = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFeesMonthly = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFeesPaid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtFeesId = new javax.swing.JTextField();
        txtPlayerName = new javax.swing.JTextField();
        txtCoachName = new javax.swing.JTextField();
        txtSportsName = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtToolName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel1.setText("Fees Structure");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 20, 292, 44));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setText("Balance");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 100, 26));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel3.setText("Coach Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 105, 26));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel4.setText("Player Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 105, 26));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel5.setText("Sports Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 105, 26));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setText("Tool Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 105, 26));

        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 140, 26));

        cmbToolId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbToolId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbToolIdItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbToolId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 180, 30));

        cmbPlayerid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlayeridItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbPlayerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 180, 30));

        cmbCoachId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbCoachId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCoachIdItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCoachId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, 30));

        cmbSportsId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbSportsId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSportsIdItemStateChanged(evt);
            }
        });
        cmbSportsId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSportsIdActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSportsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 180, 30));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel7.setText("Fees Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 95, 91, 26));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel8.setText("Fees Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 95, 91, 26));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel9.setText("Coach Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 120, 26));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel10.setText("Player Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 120, 26));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel11.setText("Sports Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 120, 26));

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel12.setText("Time");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, 26));

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel13.setText("Tool Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 100, 26));

        jLabel14.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel14.setText("Duration");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, 26));

        txtDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 182, 30));

        jLabel15.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel15.setText("Quantity");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 100, 26));

        jLabel16.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel16.setText("Sports Fees Monthly");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 180, 26));

        txtFeesMonthly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtFeesMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 140, 26));

        jLabel17.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel17.setText("Fees Paid");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 120, 26));

        txtFeesPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtFeesPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 140, 26));

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 130, 40));

        txtFeesId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtFeesId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 96, 182, 30));

        txtPlayerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 182, 30));

        txtCoachName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtCoachName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 206, 182, 30));

        txtSportsName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSportsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSportsNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSportsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 266, 182, 30));

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 326, 182, 30));

        txtToolName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtToolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToolNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtToolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 376, 182, 30));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 426, 182, 30));

        jButton2.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            String FeesId,PlayerId,PlayerName,CoachId,CoachName,SportsId,SportasName,Time,ToolId,ToolName,Quantity,SportsFessMonthly,Duration,FeesPaid,Balance;
            FeesId=txtFeesId.getText();     
            PlayerId=cmbPlayerid.getSelectedItem().toString(); 
            PlayerName=txtPlayerName.getText();
            CoachId=cmbCoachId.getSelectedItem().toString(); 
            CoachName=txtCoachName.getText();
            SportsId=cmbSportsId.getSelectedItem().toString(); 
            SportasName=txtSportsName.getText();
            Time=txtTime.getText();
            ToolId=cmbToolId.getSelectedItem().toString(); 
            ToolName=txtToolName.getText();
            Quantity=txtQuantity.getText();
            SportsFessMonthly=txtFeesMonthly.getText();
            Duration=txtDuration.getText();
            FeesPaid=txtFeesPaid.getText();
            Balance=txtBalance.getText();
            st.executeUpdate("insert into feesdetails values ('" + FeesId +"','"+ PlayerId + "','" + PlayerName + "','" + CoachId + "','" + CoachName + "','" + SportsId + "','"+ SportasName +"','"+ Time + "','" + ToolId +"','" + ToolName +"','"+ Quantity + "','"+ SportsFessMonthly +"','"+ Duration + "','"+ FeesPaid +"','"+ Balance +"')");
            con.close();
        } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbSportsIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSportsIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSportsIdActionPerformed

    private void cmbPlayeridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlayeridItemStateChanged
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from register1 where PlayerId="+cmbPlayerid.getSelectedItem()+"");
            rs.next();
            txtPlayerName.setText(rs.getString(2));
             } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_cmbPlayeridItemStateChanged

    private void cmbSportsIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSportsIdItemStateChanged
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from sportdetails where Sportsid="+cmbSportsId.getSelectedItem()+"");
            rs.next();
            txtSportsName.setText(rs.getString(2));
            txtDuration.setText(rs.getString(3));
            txtTime.setText(rs.getString(4));
             } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_cmbSportsIdItemStateChanged

    private void txtSportsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSportsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSportsNameActionPerformed

    private void cmbCoachIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCoachIdItemStateChanged
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from coachdetails where coachid="+cmbCoachId.getSelectedItem()+"");
            rs.next();
            txtCoachName.setText(rs.getString(2));
              } catch (SQLException qw) {
            System.out.println(qw);
        }
    }//GEN-LAST:event_cmbCoachIdItemStateChanged

    private void cmbToolIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbToolIdItemStateChanged
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from provides where Toolid="+cmbToolId.getSelectedItem()+"");
            rs.next();
            txtToolName.setText(rs.getString(2));
            txtQuantity.setText(rs.getString(3));
          
            
             } catch (SQLException qw) {
            System.out.println(qw);}
    }//GEN-LAST:event_cmbToolIdItemStateChanged

    private void txtToolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToolNameActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fees_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fees_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fees_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fees_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fees_9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCoachId;
    private javax.swing.JComboBox<String> cmbPlayerid;
    private javax.swing.JComboBox<String> cmbSportsId;
    private javax.swing.JComboBox<String> cmbToolId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCoachName;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtFeesId;
    private javax.swing.JTextField txtFeesMonthly;
    private javax.swing.JTextField txtFeesPaid;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSportsName;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtToolName;
    // End of variables declaration//GEN-END:variables
}
