/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author INTEGRAL COMPUTER
 */
public class Main_Dashboard_4 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Dashboard
     */
    public Main_Dashboard_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        courts_details = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        new_registration = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sports_list = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        diet_plans = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fees = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        attandancs = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        events = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        provides = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 770));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C S M B A");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 6));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\icons8-pullups-1--unscreen.gif")); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 200, 180));

        courts_details.setBackground(new java.awt.Color(102, 102, 102));
        courts_details.setForeground(new java.awt.Color(153, 153, 153));
        courts_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courts_detailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                courts_detailsMousePressed(evt);
            }
        });
        courts_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\view-details-32.png")); // NOI18N
        courts_details.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, -1, 41));

        jLabel10.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Coach Details");
        courts_details.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 11, 180, 30));

        jPanel2.add(courts_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 50));

        new_registration.setBackground(new java.awt.Color(102, 102, 102));
        new_registration.setForeground(new java.awt.Color(153, 153, 153));
        new_registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_registrationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                new_registrationMousePressed(evt);
            }
        });
        new_registration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\new_32.png")); // NOI18N
        new_registration.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Registration");
        new_registration.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 30));

        jPanel2.add(new_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 50));

        sports_list.setBackground(new java.awt.Color(102, 102, 102));
        sports_list.setForeground(new java.awt.Color(153, 153, 153));
        sports_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sports_listMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sports_listMousePressed(evt);
            }
        });
        sports_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sports List");
        sports_list.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 123, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\Sports_32.png")); // NOI18N
        sports_list.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        jPanel2.add(sports_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 50));

        edit.setBackground(new java.awt.Color(102, 102, 102));
        edit.setForeground(new java.awt.Color(153, 153, 153));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edit");
        edit.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, 180, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\news_32.png")); // NOI18N
        edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 40, 30));

        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 50));

        diet_plans.setBackground(new java.awt.Color(102, 102, 102));
        diet_plans.setForeground(new java.awt.Color(153, 153, 153));
        diet_plans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diet_plansMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                diet_plansMousePressed(evt);
            }
        });
        diet_plans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Diet Plans");
        diet_plans.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 11, 180, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\diet_32.png")); // NOI18N
        diet_plans.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, 40, 30));

        jPanel2.add(diet_plans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 50));

        fees.setBackground(new java.awt.Color(51, 51, 51));
        fees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                feesMousePressed(evt);
            }
        });
        fees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fees");
        fees.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 11, 180, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\money-bag-32.png")); // NOI18N
        fees.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 9, 36, -1));

        jPanel2.add(fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 50));

        attandancs.setBackground(new java.awt.Color(51, 51, 51));
        attandancs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attandancsMousePressed(evt);
            }
        });
        attandancs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\in_32.png")); // NOI18N
        attandancs.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, 38, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attendance");
        attandancs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 11, 180, 30));

        jPanel2.add(attandancs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 50));

        events.setBackground(new java.awt.Color(51, 51, 51));
        events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eventsMousePressed(evt);
            }
        });
        events.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\events_32.png")); // NOI18N
        events.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, 40, 30));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Events");
        events.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 11, 180, 30));

        jPanel2.add(events, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        provides.setBackground(new java.awt.Color(51, 51, 51));
        provides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                providesMousePressed(evt);
            }
        });
        provides.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Documents\\icon\\provides_32.png")); // NOI18N
        provides.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, 40, 30));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Provides");
        provides.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 180, 30));

        jPanel2.add(provides, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 50));

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 2));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 870));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Sitka Small", 0, 80)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 255, 102));
        jLabel21.setText("A");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, 70));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("cademy");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 170, 50));

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Sitka Small", 0, 80)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jLabel23.setText("C");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 90));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("hhatrapati");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 50));

        jLabel25.setFont(new java.awt.Font("Sitka Small", 0, 80)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 15));
        jLabel25.setText("S");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 70));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("hivaji");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 130, 50));

        jLabel27.setFont(new java.awt.Font("Sitka Small", 0, 80)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 102, 255));
        jLabel27.setText("M");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 90));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("aharaj");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 120, 50));

        jLabel29.setFont(new java.awt.Font("Sitka Small", 0, 80)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 204, 51));
        jLabel29.setText("B");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, 90));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("asketball");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 170, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1080, 130));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\money-bag-48.png")); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 13, 56, -1));

        jLabel50.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel50.setText("Fees");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 27, 78, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 380, 80));

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("\" If opportunity ");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, -1, 28));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("doesn't");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 51, 70, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Knock,");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 47, -1, 24));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("build a");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 79, 70, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Door.\"");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 79, 88, -1));

        jLabel36.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel36.setText("Register Now.");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 179, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\account-login-128.gif")); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 125, 142, 112));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 320, 250));

        jPanel8.setBackground(new java.awt.Color(51, 255, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\pages-2-48.gif")); // NOI18N
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, -1, 51));

        jLabel43.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel43.setText("Attendance");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 93, -1, 23));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 90, 150));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\bell-3-64.gif")); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 2, -1, 76));

        jLabel51.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel51.setText("Events");
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 28, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 380, 80));

        jPanel10.setBackground(new java.awt.Color(255, 51, 15));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\edit-11-48.png")); // NOI18N
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel53.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel53.setText("Edit");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 30, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 15));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Registration Page");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 30));

        jButton2.setBackground(new java.awt.Color(255, 51, 15));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Events");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 26));

        jButton3.setBackground(new java.awt.Color(255, 51, 15));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Sports Details");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 26));

        jButton4.setBackground(new java.awt.Color(255, 51, 15));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Provides");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 150, 26));

        jButton5.setBackground(new java.awt.Color(255, 51, 15));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Coach List");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, 26));

        jButton6.setBackground(new java.awt.Color(255, 51, 15));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Fees");
        jButton6.setBorder(new javax.swing.border.MatteBorder(null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 26));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, 310, 350));

        jPanel11.setBackground(new java.awt.Color(255, 204, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\list-rich-64.gif")); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 25, -1, 81));

        jLabel52.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel52.setText("Sports List");
        jPanel11.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 112, 116, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 250, 150));

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\view-details-48.png")); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2, -1, -1));

        jLabel49.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel49.setText("Coach Details");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, 23));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 90, 80));

        jPanel13.setBackground(new java.awt.Color(255, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\restaurant-3-48.png")); // NOI18N
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 2, 56, -1));

        jLabel48.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel48.setText("Diet Plans");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 56, -1, 23));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 90, 80));

        jPanel14.setBackground(new java.awt.Color(204, 102, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\light-bulb-2-48.png")); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2, 56, -1));

        jLabel47.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel47.setText("Provides");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, 23));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 90, 80));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\account-login-24.png")); // NOI18N
        jLabel55.setText("Registration Report");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 140, 30));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel57.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\list-rich-24.png")); // NOI18N
        jLabel57.setText("Sports Details Reports");
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 160, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel59.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\view-details-24.png")); // NOI18N
        jLabel59.setText("Coach List Report");
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 130, 30));

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel63.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\light-bulb-2-24.png")); // NOI18N
        jLabel63.setText("Provides Reports");
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 130, 30));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\money-bag-24 (1).png")); // NOI18N
        jLabel64.setText("Diet Plans Details");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 640, 130, 30));

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, 1077, 2));

        jLabel62.setText("Help & Support");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 90, 20));

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\bell-3-24.png")); // NOI18N
        jLabel65.setText("Events Reports");
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 120, 30));

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel66.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\money-bag-24 (1).png")); // NOI18N
        jLabel66.setText("Fees Reports");
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, 110, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 730, 130, 10));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\x-mark-2-32 (1).png")); // NOI18N
        jLabel54.setText("Exit");
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 70, 40));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\arrow-117-48.png")); // NOI18N
        jLabel56.setText("Back to Page");
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        new duplicate_spots_list().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new duplicate_registration().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        
         new registration_page_5().setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
         new registration_page_5().setVisible(true);
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
          new Sports_list_6().setVisible(true);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
          new Sports_list_6().setVisible(true);
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        new Event_10().setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        new Event_10().setVisible(true);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
          new Providses_7().setVisible(true);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
          new Providses_7().setVisible(true);
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        // new Diet_Plan_11().setVisible(true);
              try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\DietPlanreport1.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        // new Diet_Plan_11().setVisible(true);
             try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\DietPlanreport1.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
         new Coach_list_8().setVisible(true);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
         new Coach_list_8().setVisible(true);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
          new Fees_9().setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
          new Fees_9().setVisible(true);
    }//GEN-LAST:event_jLabel42MouseClicked

    private void new_registrationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_registrationMousePressed
        // TODO add your handling code here:
       setColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
    }//GEN-LAST:event_new_registrationMousePressed
        
     void setColor(JPanel panel)
        {
        panel.setBackground(new Color(102,102,102));
        }
    
        void resetColor(JPanel panel)
        {
         panel.setBackground(new Color(51,51,51));
        }
    private void courts_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courts_detailsMouseClicked
        // TODO add your handling code here:
       
      
       new Coach_list_8().setVisible(true);
    
    }//GEN-LAST:event_courts_detailsMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         new duplicate_coach_list().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         new duplicate_provides().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new duplicate_events().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        // new Main_Dashboard_4().setVisible(true);
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:   try
            try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\Registrationreport.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
      
        
         
      
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
           try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:/javacoding/netbeanscode/Project/src/project/Sportsreport1.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         
       
    }//GEN-LAST:event_jLabel57MouseClicked

    private void new_registrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_registrationMouseClicked
        // TODO add your handling code here:
          new registration_page_5().setVisible(true);
    }//GEN-LAST:event_new_registrationMouseClicked

    private void sports_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sports_listMouseClicked
        // TODO add your handling code here:
         new Sports_list_6().setVisible(true);
    }//GEN-LAST:event_sports_listMouseClicked

    private void eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseClicked
        // TODO add your handling code here:
        new Event_10().setVisible(true);
    }//GEN-LAST:event_eventsMouseClicked

    private void providesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providesMouseClicked
        // TODO add your handling code here:
         new Providses_7().setVisible(true);
    }//GEN-LAST:event_providesMouseClicked

    private void feesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesMouseClicked
        // TODO add your handling code here:
          new Fees_9().setVisible(true);
    }//GEN-LAST:event_feesMouseClicked

    private void attandancsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attandancsMousePressed
        // TODO add your handling code here:
         setColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
    }//GEN-LAST:event_attandancsMousePressed

    private void sports_listMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sports_listMousePressed
        // TODO add your handling code here:
         setColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
    }//GEN-LAST:event_sports_listMousePressed

    private void eventsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMousePressed
        // TODO add your handling code here:
         setColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
    }//GEN-LAST:event_eventsMousePressed

    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
        // TODO add your handling code here:
          setColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
    }//GEN-LAST:event_editMousePressed

    private void providesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providesMousePressed
        // TODO add your handling code here:
            setColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
    }//GEN-LAST:event_providesMousePressed

    private void diet_plansMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diet_plansMousePressed
        // TODO add your handling code here:
         setColor(diet_plans);
       resetColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
    }//GEN-LAST:event_diet_plansMousePressed

    private void feesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesMousePressed
        // TODO add your handling code here:
         setColor(fees);
       resetColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
    }//GEN-LAST:event_feesMousePressed

    private void courts_detailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courts_detailsMousePressed
        // TODO add your handling code here:
          setColor(courts_details);
       resetColor(new_registration);
       resetColor(attandancs);
       resetColor(sports_list);
       resetColor(events);
       resetColor(edit);
       resetColor(provides);
       resetColor(diet_plans);
       resetColor(fees);
    }//GEN-LAST:event_courts_detailsMousePressed

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
            try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\Providesreport.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        // TODO add your handling code here:
          try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\Coachreport.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        // TODO add your handling code here:
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\Eventreport.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        // TODO add your handling code here:
         try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\DietPlanreport1.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel64MouseClicked

    private void diet_plansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diet_plansMouseClicked
        // TODO add your handling code here:
             try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\DietPlanreport1.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_diet_plansMouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        // TODO add your handling code here:
            try
        {
         Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            JasperDesign js=JRXmlLoader.load("D:\\javacoding\\netbeanscode\\Project\\src\\project\\Feesreport.jrxml");
           // String query="select * from sportdetails";
            JRDesignQuery uq=new JRDesignQuery();
            //uq.setText(query);
           // js.setQuery(uq);
            JasperReport jr=JasperCompileManager.compileReport(js);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel66MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Dashboard_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attandancs;
    private javax.swing.JPanel courts_details;
    private javax.swing.JPanel diet_plans;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel events;
    private javax.swing.JPanel fees;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel new_registration;
    private javax.swing.JPanel provides;
    private javax.swing.JPanel sports_list;
    // End of variables declaration//GEN-END:variables
}
