/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author INTEGRAL COMPUTER
 */
public class Sports_list_6 extends javax.swing.JFrame {

    /**
     * Creates new form Sports_list_6
     */
    public Sports_list_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lavl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSportsid = new javax.swing.JTextField();
        txtteaching = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtduration = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 10));

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEGRAL COMPUTER\\Downloads\\arrow-241-64.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CANCLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 40));
        jPanel4.add(lavl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 170, 300));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel10.setText("Teaching Time");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 140, 40));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel11.setText("S P O R T   D E T A I L S");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 360, 40));

        jLabel12.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel12.setText("Sports Nmae");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 120, 40));

        txtSportsid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSportsid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSportsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSportsidActionPerformed(evt);
            }
        });
        jPanel5.add(txtSportsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 40));

        txtteaching.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtteaching.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtteaching, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 30));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 30));

        jLabel13.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        jLabel13.setText("Sports  Id");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 40));

        jLabel14.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel14.setText("Duration");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, 40));

        txtduration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtduration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 460, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtSportsid.getText().trim().isEmpty() )
                 {
                     
                   lavl.setText("Some Field,s are Empty ");
        
                 }
          else if (txtSportsid.getText().trim().isEmpty())
        {
            lavl.setText("Sports Field is Empty enter only Numbers");
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdetails","root","");
            Statement st = con.createStatement();
            String SportId,Name,Duration,TeachingTime;	
            SportId=txtSportsid.getText();
            Name= txtname.getText(); 
            Duration= txtduration.getText();   
            TeachingTime=txtteaching.getText(); 
            st.executeUpdate("insert into sportdetails values ('"+ SportId +"','"+ Name +"','"+ Duration +"','"+ TeachingTime +"')");
                con.close();
        } catch (SQLException qw) {
            System.out.println(qw);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSportsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSportsidActionPerformed
        // TODO add your handling code here:
         String PlayerId=txtSportsid.getText();
        if (PlayerId.matches("^[0-9]*$") && PlayerId.length()==5)
        {
            txtSportsid.setBackground(Color.green);
        }
        else
        {
            txtSportsid.setBackground(new Color(255,102,102));
        }
    }//GEN-LAST:event_txtSportsidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sports_list_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sports_list_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sports_list_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sports_list_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sports_list_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lavl;
    private javax.swing.JTextField txtSportsid;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtteaching;
    // End of variables declaration//GEN-END:variables
}
